descriptor-schema-version: "2.8"
info:
  name: iox-x86-iperf
  version: latest
  description: Alpine linux with iPerf
app:
  cpuarch: x86_64
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    TERM: xterm
  resources:
    cpu: "400"
    memory: "128"
    network:
    - interface-name: eth0
      ports:
        tcp:
          - 5002
    profile: custom
  startup:
    rootfs: rootfs.tar
    target:
    - bash
    - /idle.sh
    workdir: /root
  type: docker
